### ISSUE TITLE
Aqara Motion Sensor trigger in Home Assistant (rtcgq11lm)

### ISSUE THREAD

**Issue by LeVuHoang** [dresden-elektronik/deconz-rest-plugin#3101]
Hi,
I don't know how to make this work, I even don't need LUX value, I only need to have a trigger when there is a motion.
This is how I setup in Home Assistant
```
above: 0
below: 1000
device_id: 5dc862c8f6964b699ad303fc087d4974
domain: sensor
entity_id: sensor.living_motion_sensor
for:
  hours: 0
  minutes: 0
  seconds: 0
platform: device
type: illuminance

entity_id: light.master_light
service: light.toggle
```
I changed value of Above, Below, For, but even when LUX changed the value, it's not working
I also tried with State but doesn't work neither
```
entity_id: sensor.living_motion_sensor
platform: state
to: 'on'

entity_id: light.master_light
service: light.toggle
```
There are two entities for this motion only
```
sensor.living_motion_sensor
sensor.living_motion_sensor_battery_level
```
https://ibb.co/fY3gPF0

There is no Binary Sensor value.

I even don't care about LUX value, I just want to be triggered when there's a motion.

There is no event even I moved in front of the sensor
https://ibb.co/Wn2PG9B

This is LUX value
https://ibb.co/dcKCNzg

Deconz
https://ibb.co/bFQz31J

Thanks
