### ISSUE TITLE
modify scene cannot update colormode

### ISSUE THREAD

**Issue by vanviegen** [dresden-elektronik/deconz-rest-plugin#348]
It seems that once a colormode is chosen for a light within a scene, it cannot be changed using the /groups/*/scenes/*/lights/*/state endpoint. Is this a bug, or is there another way this should be done?

```
▶ huescript get /groups/63/scenes/1
lights:
- bri: 137
  colormode: xy
  id: "4"
  on: true
  transitiontime: 10
  x: 0.299989
  y: 0.199988
name: test
state: 0

▶ huescript put /groups/63/scenes/1/lights/4/state '{"colormode":"ct","ct":366}'
- success:
    id: "1"

▶ huescript get /groups/63/scenes/1
lights:
- bri: 137
  colormode: xy
  id: "4"
  on: true
  transitiontime: 10
  x: 0.299989
  y: 0.199988
name: test
state: 0
```

Thanks!
Frank
