### ISSUE TITLE
Add color attribute to Alert

### ISSUE THREAD

**Issue by D34DC3N73R** [dresden-elektronik/deconz-rest-plugin#3702]
## Feature request type
Add color to Alert field for use with Home Assistant [light.turn_on service](https://www.home-assistant.io/integrations/light/#service-lightturn_on) `flash`

## Description
I'd like to be able to flash a hue bulb different colors with home assistant. Currently, HA supports adding color with `light.turn_on` `flash:short/long` but the color attribute doesn't appear to be passed on through the deconz api.

## Considered alternatives
I've considered a script in home assistant that repeatedly turns the bulb off, but I'd prefer to use `flash`.

## Additional context
When I call the service, the hue rgb bulb flashes white instead of the specified color.
```
  - service: light.turn_on
    data:
      transition: 0
      brightness: 255
      color_name: orangered
      flash: long
    entity_id: light.hue_lamp
```
