### ISSUE TITLE
Liveness, Readiness, Startup Probes

### ISSUE THREAD

**Issue by 0Bu** [dresden-elektronik/deconz-rest-plugin#4473]
## Feature request type

It would be nice to have the liveness, readiness and startup probes endpoints.

## Description

This would enable the configuration of the kubernetes probes for docker containers.

## Considered alternatives

At the very moment I use httpGet with root path (/), what may be not such conclusive.

```
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 18
```
## Additional context

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
