### ISSUE TITLE
IRIS 3405-L Keypad

### ISSUE THREAD

**Issue by hansaya** [dresden-elektronik/deconz-rest-plugin#4845]
## Device

- Product name: IRIS 3405-L
- Manufacturer: CentraLite
- Model identifier: 3405-L
- Device type :
  - Other: Keypad

## Screenshots
![Iris keypad](https://user-images.githubusercontent.com/5912008/117413225-5316b500-aedb-11eb-92a5-255dd03567ac.jpg)
![image](https://user-images.githubusercontent.com/5912008/117412786-ccfa6e80-aeda-11eb-8637-8f849183c8fa.png)
![image](https://user-images.githubusercontent.com/5912008/117412123-04b4e680-aeda-11eb-8f3f-3c54aec07a88.png)

### Basic
![image](https://user-images.githubusercontent.com/5912008/117412154-10a0a880-aeda-11eb-94a5-50553cd232f5.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/5912008/117412700-b05e3680-aeda-11eb-838a-f968cfcbd96f.png)

### Power
![image](https://user-images.githubusercontent.com/5912008/117412263-329a2b00-aeda-11eb-88b4-b88e53063ada.png)

### Poll Control
![image](https://user-images.githubusercontent.com/5912008/117412326-4b0a4580-aeda-11eb-8349-6834fcbf464e.png)

### Temperature measurement
![image](https://user-images.githubusercontent.com/5912008/117412376-59586180-aeda-11eb-8939-0c004231bab5.png)

### IAS zone
![image](https://user-images.githubusercontent.com/5912008/117412505-7db43e00-aeda-11eb-8355-de78fa681b30.png)

**Comment by a1ad** [comment]
@Smanar lets go ;-)

**Comment by a1ad** [comment]
@hansaya You cant use docker. You need a linux OS like Debian or Raspbian to compile @Smanar his keypad branch..

**Comment by Smanar** [comment]
Yep it s possible with docker https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4841#issuecomment-833875719
But not realy easy, and I m not skilled enought to help you for that.

You haven't another linux machine (a VM or a raspberry) ?

**Comment by hansaya** [comment]
It doesn't matter as long as I can get some instruction to compile.

**Comment by Smanar** [comment]
To compile it s easy on classic OS, you have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch keypad_test https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

Have just mimic the other keypad code to test, will check for difference after.

But I can't explain you how to replace the file on docker ...

**Comment by hansaya** [comment]
that fine, you want me to test the keypad branch?

**Comment by Smanar** [comment]
Yep, pls, have added your device.
You have somme explanation to use it here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4758 (take care, it s not the same branch)

If you can tell me what is working or not ?
- the inclusion
- if your device use the presence sensor
- if you can see websocket return when using it
- if you can change the armed mode
- if you can change the panel mode
- ect ...

**Comment by hansaya** [comment]
I compiled it and injected it to my container. When I started to pair again it recognize as a temperature device and seems to not complete pairing process. It keeps blinking.
![image](https://user-images.githubusercontent.com/5912008/118092561-e0ea1880-b391-11eb-8668-1835eec6d64f.png)
![image](https://user-images.githubusercontent.com/5912008/118092599-ecd5da80-b391-11eb-910e-c19480a61212.png)

**Comment by Smanar** [comment]
Ok So I have a look on your device, and it seem it realy work than the one aleady added.
But to test it, I realy don't know HA, perhaps @Kane610 can explain how to install his code ?

Do you know how to use the api ? to send request to the device ?

You can too, just looking logs in deconz (with "IAS" and "info") , and use it, you will see somereturn in logs.

**Comment by Kane610** [comment]
Hass support was released last week so it's already out in the open with HASS 2021.5 :)

**Comment by Smanar** [comment]
Ha but it s already released in official version ...

So what is missing to test the device ? A problem in deconz json ? Just need to install your blueprint ?

**Comment by a1ad** [comment]
Hey can watch for the deconz events first

**Comment by Kane610** [comment]
Yes the blueprint and to try the different states because it's in an unknown state right now

**Comment by Smanar** [comment]
Do you need more explanation @hansaya ?

**Comment by hansaya** [comment]
After playing around with it,
* Arming and disarming seems to work changes the color of the keypad.
* Temperature readout seems to work.
* **Battery level indication is wrong**.
* Presence sensor works.
* Tempered indicator seems to work.
* I **cannot arm or disarm** through the keypad.
* **Cannot read the keypad code or set it**.
![image](https://user-images.githubusercontent.com/5912008/118418652-d88a2a00-b67e-11eb-9c90-492ca238d27e.png)

**Comment by Smanar** [comment]
>Battery level indication is wrong.

Yep, have corrected something, not yet online.

>I cannot arm or disarm through the keypad.

This is not possible, the device is a dummy one, when you use the keypad, it need to send a notification to third app, and it s it that arm or disarm the device.

>Cannot read the keypad code or set it.

When you type a code, you need to have a notification through websocket.

If you are using HA (It s the only one application that can manage the device ATM) I think you need this blueprint to manage code https://community.home-assistant.io/t/deconz-simple-alarm-control-panel-blueprint/305397

**Comment by a1ad** [comment]
@Smanar like i said: he need to watch for decoz events in the HA dev tools.

**Comment by hansaya** [comment]
Thanks for link on the blueprint. It worked!
Could someone explain how to get deconz event? What I should be doing right before getting it etc..

**Comment by a1ad** [comment]
> Thanks for link on the blueprint. It worked!
> Could someone explain how to get deconz event? What I should be doing right before getting it etc..

You dont need the events if the BP is working :-)

I am using the keypad with the Alarmo plugin and have 2 automations made to tie them together:

Alarmo to keypad:

```
alias: alarmo-to-keypad
description: ''
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarmo
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: alarm_control_panel.alarmo
            state: armed_away
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            target:
              device_id: 8f995b9f01fae89eef5a5e3107d2c719
      - conditions:
          - condition: state
            entity_id: alarm_control_panel.alarmo
            state: armed_home
        sequence:
          - service: alarm_control_panel.alarm_arm_home
            target:
              device_id: 8f995b9f01fae89eef5a5e3107d2c719
      - conditions:
          - condition: state
            entity_id: alarm_control_panel.alarmo
            state: armed_night
        sequence:
          - service: alarm_control_panel.alarm_arm_night
            target:
              device_id: 8f995b9f01fae89eef5a5e3107d2c719
      - conditions:
          - condition: state
            entity_id: alarm_control_panel.alarmo
            state: disarmed
        sequence:
          - service: alarm_control_panel.alarm_disarm
            target:
              device_id: 8f995b9f01fae89eef5a5e3107d2c719
      - conditions:
          - condition: state
            entity_id: alarm_control_panel.alarmo
            state: triggered
        sequence:
          - service: alarm_control_panel.alarm_trigger
            target:
              device_id: 8f995b9f01fae89eef5a5e3107d2c719
      - conditions:
          - condition: state
            entity_id: alarm_control_panel.alarmo
            state: arming
        sequence:
          - service: deconz.alarm_panel_state
            data:
              panel_state: exit_delay
            target:
              device_id: 8f995b9f01fae89eef5a5e3107d2c719
      - conditions:
          - condition: state
            entity_id: alarm_control_panel.alarmo
            state: pending
        sequence:
          - service: deconz.alarm_panel_state
            target:
              device_id: 8f995b9f01fae89eef5a5e3107d2c719
            data:
              panel_state: entry_delay
    default: []
mode: single
``` 

Keypad to alarmo:

```
alias: keypad-to-alarmo
description: ''
trigger:
  - platform: event
    event_type: deconz_alarm_event
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.event == "armed_away" }}'
        sequence:
          - service: alarmo.arm
            data:
              entity_id: alarm_control_panel.alarmo
              code: '{{ trigger.event.data.code }}'
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.event == "armed_night" }}'
        sequence:
          - service: alarmo.arm
            data:
              entity_id: alarm_control_panel.alarmo
              code: '{{ trigger.event.data.code }}'
              mode: night
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.event == "armed_home" }}'
        sequence:
          - service: alarmo.arm
            data:
              entity_id: alarm_control_panel.alarmo
              code: '{{ trigger.event.data.code }}'
              mode: home
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.event == "disarmed" }}'
        sequence:
          - service: alarmo.disarm
            data:
              entity_id: alarm_control_panel.alarmo
              code: '{{ trigger.event.data.code }}'
    default: []
mode: single

```
