### ISSUE TITLE
Jung wall switch stops working within 12 hours

### ISSUE THREAD

**Issue by RezzZ** [dresden-elektronik/deconz-rest-plugin#6601]
## Describe the bug
  Jung wall switch stops working within 12 hours

## Steps to reproduce the behavior
  Pair a jung wall switch (8 buttons). Device works fine. All buttons are programmable.
  wait a few hours (eg 12 hours)
  buttonpresses are no longer registered
  repairing works and all assigned buttons start to work again
  wait a few hours again and the device again is no longer working

## Expected behavior
  After pairing the device should not be 'forgotten'.

## Screenshots
  No screens possible for nonresponding phoscon to jung wall switch button presses.

## Environment
  My GUI doesnt show an about DeCONZ option under Menu > Help

 - Host system: Raspberry Pi3b+
 - Running method: raspbian docker deconzcommunity/deconz:stable
 - Firmware version: 26680700
 - deCONZ version: 2.19.01 / 19/09/2022
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
  Hmm, also no debug view available

## Additional context
docker-compose part:
```
  deconz:
    container_name: deconz
    image: deconzcommunity/deconz:stable
    network_mode: host
    restart: always
    volumes:
      - /opt/deconz:/opt//deCONZ
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DECONZ_DEVICE=/dev/ttyACM1
#      - DECONZ_VNC_MODE=1
    devices:
      - /dev/ttyACM1
```
